### ISSUE TITLE
ssb-validate@4.1.1 breaks gossip?

### ISSUE THREAD

**Issue by regular** [ssb-js/ssb-validate#23]
I noticed that ssb-server/test/caps.js fails with ssb-validate@4.1.1 because ssb-validate now expects caps.sign to be base64 encoded. I changed the test to use base64 and it passed. However, if you let the test run a little longer (putting `test.only` there, so the cleanup doesn't happen), you'll see the invalid HMAC error showing up again, which, so my current understanding, tells us that ssb-validate prevents gossiping because of the keys used not being base64 encoded. Plain buffers used to be ok, now they are not, I think that might break gossip, not sure though.

**Comment by regular** [comment]
@christianbundy

**Comment by christianbundy** [comment]
Oh, thanks for pointing this out! I'll open a PR now.
